# 1. Reactome

In [1]:
import pandas as pd
import numpy as np
from network.gmt_reader import GMT

In [2]:
# https://reactome.org/download/current/ReactomePathways.txt
# Pathways: reactome_id, pathway_name, species
pathways = pd.read_csv('../_database/pathways/Reactome2023/ReactomePathways.txt',sep='\t')
pathways.columns = ['reactome_id', 'pathway_name', 'species']
pathways = pathways[pathways.species == 'Homo sapiens'].reset_index(drop=True)
pathways.drop('species', inplace=True,axis=1)

# https://reactome.org/download/current/ReactomePathwaysRelation.txt
# hierarchy: parent, child
hierarchy = pd.read_csv('../_database/pathways/Reactome2023/ReactomePathwaysRelation.txt', sep='\t')
hierarchy.columns = ['parent', 'child']
hierarchy = hierarchy[hierarchy['child'].str.contains('HSA')].reset_index(drop=True)

# https://reactome.org/download/current/ReactomePathways.gmt.zip
# gene_pathway: reactome_id, gene
gmt = GMT()
gene_pathway = gmt.load_data('../_database/pathways/Reactome2023/ReactomePathways.gmt', pathway_col=1, genes_col=3)
gene_pathway.columns = ['reactome_id', 'gene']

# https://reactome.org/download-data#:~:text=Complexes%20to%20Pathways%20(Human)
# complex_pathway: complex, pathway, top_level_pathway
complex_pathway = pd.read_csv('../_database/pathways/Reactome2023/Complex_2_Pathway_human.txt',sep='\t')
complex_pathway = complex_pathway[complex_pathway['complex'].str.contains('HSA')].reset_index(drop=True)

# https://reactome.org/download/current/Ewas2Pathway_human.txt
# Ewas: ewas, pathway, top_level_pathway
Ewas = pd.read_csv('../_database/pathways/Reactome2023/Ewas2Pathway_human.txt',sep='\t')
Ewas = Ewas[Ewas['ewas'].str.contains('HSA')].reset_index(drop=True)

# https://reactome.org/download/tools/ReatomeFIs/FIsInGene_070323_with_annotations.txt.zip
# FIS: Gene1, Gene2, Annotation, Direction, Score
FIS = pd.read_csv('../_database/pathways/Reactome2023/FIsInGene_070323_with_annotations.txt',sep='\t')

In [3]:
print('pathways shape: ', pathways.shape)
print('\tUniuqe reactome_id: ', pathways.reactome_id.nunique())
print('\tUniuqe pathway_name: ', pathways.pathway_name.nunique())
pathways

pathways shape:  (2629, 2)
	Uniuqe reactome_id:  2629
	Uniuqe pathway_name:  2612

        reactome_id                                       pathway_name
0      R-HSA-164843                             2-LTR circle formation
1       R-HSA-73843         5-Phosphoribose 1-diphosphate biosynthesis
2     R-HSA-1971475  A tetrasaccharide linker sequence is required ...
3     R-HSA-5619084                          ABC transporter disorders
4     R-HSA-1369062              ABC transporters in lipid homeostasis
...             ...                                                ...
2624  R-HSA-9703009                   tamatinib-resistant FLT3 mutants
2625  R-HSA-9702636                  tandutinib-resistant FLT3 mutants
2626   R-HSA-199992                trans-Golgi Network Vesicle Budding
2627   R-HSA-192814                                     vRNA Synthesis
2628   R-HSA-192905                                      vRNP Assembly

[2629 rows x 2 columns]

In [4]:
print('hierarchy shape: ', hierarchy.shape)
print('\tUniuqe parent: ', hierarchy.parent.nunique())
print('\tUniuqe child: ', hierarchy.child.nunique())
hierarchy

hierarchy shape:  (2647, 2)
	Uniuqe parent:  782
	Uniuqe child:  2600

            parent          child
0     R-HSA-109581   R-HSA-109606
1     R-HSA-109581   R-HSA-169911
2     R-HSA-109581  R-HSA-5357769
3     R-HSA-109581    R-HSA-75153
4     R-HSA-109582   R-HSA-140877
...            ...            ...
2642  R-HSA-983705   R-HSA-983695
2643  R-HSA-983712  R-HSA-2672351
2644  R-HSA-983712   R-HSA-936837
2645  R-HSA-991365   R-HSA-170670
2646  R-HSA-991365   R-HSA-997272

[2647 rows x 2 columns]

In [5]:
print('gene_pathway shape: ', gene_pathway.shape)
print('\tUniuqe reactome_id: ', gene_pathway.reactome_id.nunique())
print('\tUniuqe gene: ', gene_pathway.gene.nunique())
gene_pathway

gene_pathway shape:  (126204, 2)
	Uniuqe reactome_id:  2342
	Uniuqe gene:  11488

         reactome_id   gene
0       R-HSA-164843  HMGA1
1       R-HSA-164843   LIG4
2       R-HSA-164843  PSIP1
3       R-HSA-164843  XRCC4
4       R-HSA-164843  XRCC5
...              ...    ...
126199  R-HSA-192905     NP
126200  R-HSA-192905     NS
126201  R-HSA-192905     PA
126202  R-HSA-192905    PB1
126203  R-HSA-192905    PB2

[126204 rows x 2 columns]

In [6]:
print('complex_pathway shape: ', complex_pathway.shape)
print('\tUniuqe complex: ', complex_pathway.complex.nunique())
print('\tUniuqe pathway: ', complex_pathway.pathway.nunique())
print('\tUniuqe top_level_pathway: ', complex_pathway.top_level_pathway.nunique())
complex_pathway

complex_pathway shape:  (23460, 3)
	Uniuqe complex:  13987
	Uniuqe pathway:  1781
	Uniuqe top_level_pathway:  29

             complex       pathway top_level_pathway
0      R-HSA-1006173  R-HSA-977606      R-HSA-168256
1      R-HSA-1008206  R-HSA-983231      R-HSA-109582
2      R-HSA-1008229  R-HSA-983231      R-HSA-109582
3      R-HSA-1008252  R-HSA-983231      R-HSA-109582
4      R-HSA-1011577  R-HSA-983231      R-HSA-109582
...              ...           ...               ...
23455   R-HSA-997243  R-HSA-983231      R-HSA-109582
23456   R-HSA-997300  R-HSA-912694      R-HSA-168256
23457   R-HSA-997302  R-HSA-912694      R-HSA-168256
23458   R-HSA-997303  R-HSA-912694      R-HSA-168256
23459   R-HSA-997304  R-HSA-912694      R-HSA-168256

[23460 rows x 3 columns]

In [7]:
print('Ewas shape: ', Ewas.shape)
print('\tUniuqe complex: ', Ewas.ewas.nunique())
print('\tUniuqe pathway: ', Ewas.pathway.nunique())
print('\tUniuqe top_level_pathway: ', Ewas.top_level_pathway.nunique())
Ewas

Ewas shape:  (72906, 3)
	Uniuqe complex:  30025
	Uniuqe pathway:  2101
	Uniuqe top_level_pathway:  29

                ewas        pathway top_level_pathway
0      R-HSA-1008196  R-HSA-1237044      R-HSA-382551
1      R-HSA-1008196  R-HSA-1247673      R-HSA-382551
2      R-HSA-1008196  R-HSA-9613829     R-HSA-9612973
3      R-HSA-1008196  R-HSA-9615710     R-HSA-9612973
4      R-HSA-1008196   R-HSA-983231      R-HSA-109582
...              ...            ...               ...
72901   R-HSA-997253   R-HSA-983231      R-HSA-109582
72902   R-HSA-997258   R-HSA-983231      R-HSA-109582
72903   R-HSA-997292  R-HSA-6807004      R-HSA-162582
72904   R-HSA-997294   R-HSA-877312      R-HSA-168256
72905   R-HSA-997295   R-HSA-877312      R-HSA-168256

[72906 rows x 3 columns]

In [8]:
print('FIS shape: ', FIS.shape)
print('\tUniuqe Gene1: ', FIS.Gene1.nunique())
print('\tUniuqe Gene2: ', FIS.Gene2.nunique())
print('\tUniuqe Direction: ', FIS.Direction.nunique())
FIS

FIS shape:  (278974, 5)
	Uniuqe Gene1:  11896
	Uniuqe Gene2:  12254
	Uniuqe Direction:  9

         Gene1    Gene2                    Annotation Direction  Score
0         A1CF  APOBEC1  catalyzed by; complex; input        <-   1.00
1         A1CF    CELF2                     predicted         -   0.90
2         A1CF    EP300       expression regulated by        <-   1.00
3         A1CF    RBM47                     predicted         -   0.89
4          A2M    APOA1                       inhibit        -|   1.00
...        ...      ...                           ...       ...    ...
278969    ZW10   ZWILCH                complex; input         -   1.00
278970    ZW10    ZWINT                complex; input         -   1.00
278971  ZWILCH    ZWINT                complex; input         -   1.00
278972    ZXDA     ZXDB                     predicted         -   0.95
278973    ZXDA     ZXDC                     predicted         -   0.98

[278974 rows x 5 columns]

In [9]:
p = set(pathways.reactome_id)
h1 = set(hierarchy.parent)
h2 = set(hierarchy.child)
g = set(gene_pathway.reactome_id)

c1 = set(complex_pathway.complex)
c2 = set(complex_pathway.pathway)
c3 = set(complex_pathway.top_level_pathway)
E1 = set(Ewas.ewas)
E2 = set(Ewas.pathway)
E3 = set(Ewas.top_level_pathway)

In [10]:
# you can find top level pathways from complex_pathway
pathways[pathways.reactome_id.isin(c3)]

        reactome_id                          pathway_name
186   R-HSA-9612973                             Autophagy
311   R-HSA-1640170                            Cell Cycle
319   R-HSA-1500931               Cell-Cell communication
328   R-HSA-8953897         Cellular responses to stimuli
344   R-HSA-4839726                Chromatin organization
351    R-HSA-400253                       Circadian Clock
426     R-HSA-73894                            DNA Repair
427     R-HSA-69306                       DNA Replication
706   R-HSA-1266738                 Developmental Biology
708   R-HSA-8963743              Digestion and absorption
713   R-HSA-1643685                               Disease
761   R-HSA-9748784                             Drug ADME
847   R-HSA-1474244     Extracellular matrix organization
995     R-HSA-74160       Gene expression (Transcription)
1066   R-HSA-109582                            Hemostasis
1117   R-HSA-168256                         Immune System
1348  R-HSA-1430728                            Metabolism
1350  R-HSA-8953854                     Metabolism of RNA
1366   R-HSA-392499                Metabolism of proteins
1422   R-HSA-397014                    Muscle contraction
1511   R-HSA-112316                       Neuronal System
1565  R-HSA-1852241  Organelle biogenesis and maintenance
1721  R-HSA-5357801                 Programmed Cell Death
1730  R-HSA-9609507                  Protein localization
1962  R-HSA-1474165                          Reproduction
2088  R-HSA-9709957                    Sensory Perception
2104   R-HSA-162582                   Signal Transduction
2480   R-HSA-382551          Transport of small molecules
2524  R-HSA-5653656            Vesicle-mediated transport

In [11]:
top_level_gene = gene_pathway[gene_pathway.reactome_id.isin(c3)]
top_level_gene.gene.nunique()

11488

In [12]:
pathways[pathways.reactome_id=='R-HSA-9612973']

       reactome_id pathway_name
186  R-HSA-9612973    Autophagy

In [13]:
top_genes = gene_pathway.loc[gene_pathway.reactome_id=='R-HSA-9612973','gene']

In [14]:
hierarchy[hierarchy.parent=='R-HSA-9612973']

             parent          child
2327  R-HSA-9612973  R-HSA-1632852
2328  R-HSA-9612973  R-HSA-9613829
2329  R-HSA-9612973  R-HSA-9615710

In [15]:
child1_genes = gene_pathway.loc[gene_pathway.reactome_id=='R-HSA-1632852','gene']
child2_genes = gene_pathway.loc[gene_pathway.reactome_id=='R-HSA-9613829','gene']
child3_genes = gene_pathway.loc[gene_pathway.reactome_id=='R-HSA-9615710','gene']

In [16]:
child1_genes

58993    ARL13B
58994     ATG10
58995    ATG101
58996     ATG12
58997     ATG13
          ...
59124       VIM
59125     WDR45
59126    WDR45B
59127     WIPI1
59128     WIPI2
Name: gene, Length: 136, dtype: object

In [17]:
hierarchy[hierarchy.parent=='R-HSA-1632852']

            parent          child
379  R-HSA-1632852  R-HSA-9663891

In [18]:
child1_1_genes = gene_pathway.loc[gene_pathway.reactome_id=='R-HSA-9663891','gene']

In [19]:
set(child1_1_genes).union(set(child1_genes))

{'ARL13B',
 'ATG10',
 'ATG101',
 'ATG12',
 'ATG13',
 'ATG14',
 'ATG16L1',
 'ATG3',
 'ATG4A',
 'ATG4B',
 'ATG4C',
 'ATG4D',
 'ATG5',
 'ATG7',
 'ATG9A',
 'ATG9B',
 'ATM',
 'BECN1',
 'CETN1',
 'CFTR',
 'CHMP2A',
 'CHMP2B',
 'CHMP3',
 'CHMP4A',
 'CHMP4B',
 'CHMP4C',
 'CHMP6',
 'CHMP7',
 'CSNK2A1',
 'CSNK2A2',
 'CSNK2B',
 'DYNC1H1',
 'DYNC1I1',
 'DYNC1I2',
 'DYNC1LI1',
 'DYNC1LI2',
 'DYNLL1',
 'DYNLL2',
 'EPAS1',
 'FUNDC1',
 'GABARAP',
 'GABARAPL1',
 'GABARAPL2',
 'GABARAPL3',
 'HDAC6',
 'HSF1',
 'HSP90AA1',
 'HSPA8',
 'IFT88',
 'LAMTOR1',
 'LAMTOR2',
 'LAMTOR3',
 'LAMTOR4',
 'LAMTOR5',
 'MAP1LC3A',
 'MAP1LC3B',
 'MAP1LC3C',
 'MFN1',
 'MFN2',
 'MLST8',
 'MTERF3',
 'MTMR14',
 'MTMR3',
 'MTOR',
 'NBR1',
 'PARK2',
 'PARK7',
 'PCNT',
 'PEX5',
 'PGAM5',
 'PIK3C3',
 'PIK3R4',
 'PINK1',
 'PLIN2',
 'PLIN3',
 'PRKAA1',
 'PRKAA2',
 'PRKAB1',
 'PRKAB2',
 'PRKAG1',
 'PRKAG2',
 'PRKAG3',
 'RB1CC1',
 'RHEB',
 'RPS27A',
 'RPTOR',
 'RRAGA',
 'RRAGB',
 'RRAGC',
 'RRAGD',
 'SLC38A9',
 'SQSTM1',
 'SRC',
 'TOMM20',
 'TOMM22',
 'TOMM40',
 'TOMM5',
 'TOMM6',
 'TOMM7',
 'TOMM70',
 'TSC1',
 'TSC2',
 'TUBA1A',
 'TUBA1B',
 'TUBA1C',
 'TUBA3C',
 'TUBA3D',
 'TUBA3E',
 'TUBA4A',
 'TUBA4B',
 'TUBA8',
 'TUBAL3',
 'TUBB1',
 'TUBB2A',
 'TUBB2B',
 'TUBB3',
 'TUBB4A',
 'TUBB4B',
 'TUBB6',
 'TUBB8',
 'TUBB8B',
 'UBA52',
 'UBB',
 'UBC',
 'UBE2N',
 'UBE2V1',
 'ULK1',
 'USP30',
 'UVRAG',
 'VCP',
 'VDAC1',
 'VIM',
 'WDR45',
 'WDR45B',
 'WIPI1',
 'WIPI2'}

In [20]:
l=[]
for i in gene_pathway.gene:
    if i[0].islower():
        l.append(i)

In [21]:
len(l)

743

In [22]:
# all hierarchy(parent, child) have information in pathways(pathway_name)
print(len(h1.union(h2)))
print(len(p))

2629
2629

In [23]:
# 287 pathways do not have assigned genes 
print(len(g))
print(len(p) - len(g))

2342
287

In [24]:
# complex column of complex_pathway have no intersection with reactom_id of pathways
print(len(p.intersection(c1)))
print(len(p.intersection(c2)))
print(len(p.intersection(c3)))

0
1781
29

In [25]:
print(c1.intersection(c2))
print(c1.intersection(c3))
print(c2.intersection(c3))

set()
set()
set()

In [26]:
# complex column of complex_pathway have no intersection with hierarchy
print(len(h1.intersection(c1)))
print(len(h1.intersection(c2)))
print(len(h1.intersection(c3)))

print(len(h2.intersection(c1)))
print(len(h2.intersection(c2)))
print(len(h2.intersection(c3)))

0
283
29
0
1781
0

In [27]:
print(len(p.intersection(E1)))
print(len(p.intersection(E2)))
print(len(p.intersection(E3)))

0
2101
29

In [28]:
FIS

         Gene1    Gene2                    Annotation Direction  Score
0         A1CF  APOBEC1  catalyzed by; complex; input        <-   1.00
1         A1CF    CELF2                     predicted         -   0.90
2         A1CF    EP300       expression regulated by        <-   1.00
3         A1CF    RBM47                     predicted         -   0.89
4          A2M    APOA1                       inhibit        -|   1.00
...        ...      ...                           ...       ...    ...
278969    ZW10   ZWILCH                complex; input         -   1.00
278970    ZW10    ZWINT                complex; input         -   1.00
278971  ZWILCH    ZWINT                complex; input         -   1.00
278972    ZXDA     ZXDB                     predicted         -   0.95
278973    ZXDA     ZXDC                     predicted         -   0.98

[278974 rows x 5 columns]

# 2. MsigDB

## 2.1 KEGG & Reactome

In [ ]:
# https://www.gsea-msigdb.org/gsea/msigdb/download_file.jsp?filePath=/msigdb/release/2023.1.Hs/c2.cp.kegg.v2023.1.Hs.symbols.gmt
# kegg: pathway, gene
gmt = GMT()
kegg = gmt.load_data('../_database/pathways/MsigDB2023/c2.cp.kegg.v2023.1.Hs.symbols.gmt', pathway_col=0, genes_col=3)
kegg.columns = ['pathway', 'gene']

# https://www.gsea-msigdb.org/gsea/msigdb/download_file.jsp?filePath=/msigdb/release/2023.1.Hs/c2.cp.reactome.v2023.1.Hs.symbols.gmt
# reactome: pathway, gene
gmt = GMT()
reactome = gmt.load_data('../_database/pathways/MsigDB2023/c2.cp.reactome.v2023.1.Hs.symbols.gmt', pathway_col=0, genes_col=3)
reactome.columns = ['pathway', 'gene']

In [ ]:
print('kegg shape: ', kegg.shape)
print('\tUniuqe pathway: ', kegg.pathway.nunique())
print('\tUniuqe gene: ', kegg.gene.nunique())
kegg

In [ ]:
print('reactome shape: ', reactome.shape)
print('\tUniuqe pathway: ', reactome.pathway.nunique())
print('\tUniuqe gene: ', reactome.gene.nunique())
reactome

### Temp

In [ ]:
reactome[reactome.pathway=='REACTOME_INTERLEUKIN_6_SIGNALING'].gene

In [ ]:
print(reactome.pathway.nunique())
print(reactome.gene.nunique())

In [ ]:
pathways

In [ ]:
pathways.pathway_name.nunique()

In [ ]:
pathways[pathways['pathway_name'].str.contains('Interleukin')]

In [ ]:
R-HSA-6783589

In [ ]:
gene_pathway[gene_pathway.reactome_id == 'R-HSA-6783589']

In [ ]:
TYK2
1       CBL
2     STAT1
3     IL6ST
4       IL6
5      IL6R
6      JAK1
7     STAT3
8    PTPN11
9     SOCS3

## 2.2 Regulatory target gene sets

In [ ]:
# https://www.gsea-msigdb.org/gsea/msigdb/download_file.jsp?filePath=/msigdb/release/2023.1.Hs/c3.mir.mirdb.v2023.1.Hs.symbols.gmt
# mirdb: pathway, gene
gmt = GMT()
mirdb = gmt.load_data('../_database/pathways/MsigDB2023/c3.mir.mirdb.v2023.1.Hs.symbols.gmt', pathway_col=0, genes_col=3)
mirdb.columns = ['pathway', 'gene']

# https://www.gsea-msigdb.org/gsea/msigdb/download_file.jsp?filePath=/msigdb/release/2023.1.Hs/c3.tft.v2023.1.Hs.symbols.gmt
# tft: pathway, gene
gmt = GMT()
tft = gmt.load_data('../_database/pathways/MsigDB2023/c3.tft.v2023.1.Hs.symbols.gmt', pathway_col=0, genes_col=3)
tft.columns = ['pathway', 'gene']

In [ ]:
print('mirdb shape: ', mirdb.shape)
print('\tUniuqe pathway: ', mirdb.pathway.nunique())
print('\tUniuqe gene: ', mirdb.gene.nunique())
mirdb

In [ ]:
print('tft shape: ', tft.shape)
print('\tUniuqe pathway: ', tft.pathway.nunique())
print('\tUniuqe gene: ', tft.gene.nunique())
tft

# 3. Data

In [29]:
import numpy as np
import importlib
from data.data_reader import Data
%load_ext autoreload
%autoreload 2

# from preprocessing import pre
Data_params_file = 'Configs/Data_params.py'
loader = importlib.machinery.SourceFileLoader('Data_params', Data_params_file)
Data_params = loader.load_module()

In [30]:
data = Data(**Data_params.data_base)

WARNING:root:some genes dont exist in the original data set
WARNING:root:some genes dont exist in the original data set
WARNING:root:some genes dont exist in the original data set

In [31]:
data_gene = set(data.columns.levels[0])
reactome_gene = set(gene_pathway.gene)

In [32]:
len(data_gene)

9229

In [33]:
len(reactome_gene)

11488

In [34]:
# intersection of data genes and reactome genes 
len(data_gene.intersection(reactome_gene))

5669

In [35]:
for i in reactome_gene:
    if i.__contains__(' ') or i.__contains__('/'):
        print(i)

7SL RNA (ENSG00000222619)
CSF2 gene
Hh5 strain Merlin complete genome
28S rRNA
5.8S rRNA
7SL RNA (ENSG00000222639)
MAPK6 gene
5S rRNA
45S pre-rRNA gene
POU5F1 (OCT4)
UL112/UL113
FKBP14 gene
SARS coronavirus, complete genome
UL119/UL118
EPAS1 (HIF2A)

In [36]:
mut_df = pd.read_csv('_database/processed/P1000_final_analysis_set_cross_important_only.csv')
cnv_df = pd.read_csv('_database/processed/P1000_data_CNA_paper.csv')

In [37]:
mut_gene = set(mut_df.columns[1:])
cnv_gene = set(cnv_df.columns[1:])

In [38]:
len(mut_gene.intersection(cnv_gene))

8434

# 4. Network

In [39]:
from network.network_builder import get_tissue_specific_maps
import pandas as pd

In [40]:
# select tissues name from gtex and append it in Network_params.tissues list 
Network_params_file = 'Configs/Network_params.py'
loader = importlib.machinery.SourceFileLoader('Network_params', Network_params_file)
Network_params = loader.load_module()

In [41]:
# TIME-CONSUMING  ALERT!!!!!!!!!!!!! 
# insted of runing this cell multiple times,
# save the tissue_maps and load for next time trainig
# tissue_maps = get_tissue_specific_maps(genes=data.columns.levels[0],
#                                        Network_params=Network_params)

In [42]:
# for the first time save it 
# import pickle
# with open('tissue_maps.pkl', 'wb') as f:
#     pickle.dump(tissue_maps, f)

In [48]:
# for the second time load it 
import pickle
with open('tissues_maps.pkl', 'rb') as f:
    tissues_maps = pickle.load(f)

In [49]:
tissues_maps.keys()

dict_keys(['Thyroid', 'Testis', 'Pancreas', 'Stomach', 'Prostate'])

In [50]:
for t in tissues_maps.keys():
    print(t)
    for i in range(len(tissues_maps[t])):
        print(f"{i+1}, shape:{tissues_maps[t][i].shape}, connection: {sum(tissues_maps[t][i].sum(axis=1)>0)}")   
    print("#"*50, "\n")

Thyroid
1, shape:(8435, 1616), connection: 4501
2, shape:(1616, 1120), connection: 1616
3, shape:(1120, 505), connection: 1120
4, shape:(505, 169), connection: 505
5, shape:(169, 29), connection: 169
6, shape:(29, 1), connection: 29
##################################################

Testis
1, shape:(9004, 1616), connection: 4770
2, shape:(1616, 1120), connection: 1616
3, shape:(1120, 505), connection: 1120
4, shape:(505, 169), connection: 505
5, shape:(169, 29), connection: 169
6, shape:(29, 1), connection: 29
##################################################

Pancreas
1, shape:(8390, 1616), connection: 4500
2, shape:(1616, 1120), connection: 1616
3, shape:(1120, 505), connection: 1120
4, shape:(505, 169), connection: 505
5, shape:(169, 29), connection: 169
6, shape:(29, 1), connection: 29
##################################################

Stomach
1, shape:(8436, 1616), connection: 4518
2, shape:(1616, 1120), connection: 1616
3, shape:(1120, 505), connection: 1120
4, shape:(505, 169), connection: 505
5, shape:(169, 29), connection: 169
6, shape:(29, 1), connection: 29
##################################################

Prostate
1, shape:(8474, 1616), connection: 4520
2, shape:(1616, 1120), connection: 1616
3, shape:(1120, 505), connection: 1120
4, shape:(505, 169), connection: 505
5, shape:(169, 29), connection: 169
6, shape:(29, 1), connection: 29
##################################################

# 5. Cytoscape

##  5.1 Reactome

In [51]:
from network.reactome import ReactomeNetwork
import networkx as nx

In [52]:
R = ReactomeNetwork()

In [53]:
net = R.netx

In [54]:
layer_nodes = []
for i in range(11):
    distance = i
    nodes = set(nx.ego_graph(net, 'root', radius=distance))
    # remove nodes that are not **at** the specified distance but closer
    if distance >= 1.:
        nodes -= set(nx.ego_graph(net, 'root', radius=distance - 1))
    layer_nodes.append(nodes)

In [55]:
layer_num = [len(x) for x in layer_nodes]
layer_num

[1, 29, 169, 459, 840, 742, 257, 90, 36, 6, 1]

In [56]:
reactome_id=[]
distance_from_root=[]
node_gene_num=[]
for ldx, l in enumerate(layer_nodes):
    for n in l:
        reactome_id.append(n)
        distance_from_root.append(ldx)
        node_gene_num.append(len(gene_pathway.loc[gene_pathway.reactome_id == n,'gene']))

In [57]:
df = pd.DataFrame({'reactome_id':reactome_id,
                   'distance_from_root':distance_from_root,
                   'node_gene_num':node_gene_num})
df = df.drop(0)

In [58]:
reactome_node = pd.merge(df, pathways, on='reactome_id', how='left')  # 'inner' merge keeps common rows

In [59]:
hierarchy.to_csv('../../Cytoscape_data/Reactome_edge.csv')
reactome_node.to_csv('../../Cytoscape_data/Reactome_node.csv')

## 5.2 Tissue Maps

In [60]:
tissue_name = 'Prostate'
prostate_maps = tissue_maps[tissue_name]

In [61]:
# get edges from maps 
def get_edges(maps, gene_included=False):
    child = []
    parent = []
    if gene_included: x = 0 
    else: x = 1  
        
    for idx, mapp in enumerate(maps[x:-1]):
        new_child = mapp.index[mapp.sum(axis=1).values.astype(bool)].tolist()
        for jdx, c in enumerate(new_child):
            new_parent = mapp.columns[mapp.loc[c].values.astype(bool)]
            for p in new_parent:
                child.append(c)
                parent.append(p)

    edge_df = pd.DataFrame({'child': child, 'parent': parent})
    return edge_df

In [62]:
maps_edge = get_edges(prostate_maps)

In [64]:
# Create a directed graph
G = nx.DiGraph()

# Add edges to the graph
edges = [(row['parent'],row['child']) for _, row in maps_edge.iterrows()]
G.add_edges_from(edges)

In [65]:
roots = [n for n, d in G.in_degree() if d == 0]
root_node = 'root'
edges = [(root_node, n) for n in roots]
G.add_edges_from(edges)

In [66]:
layer_nodes = []
for i in range(11):
    distance = i
    nodes = set(nx.ego_graph(G, 'root', radius=distance))
    # remove nodes that are not **at** the specified distance but closer
    if distance >= 1.:
        nodes -= set(nx.ego_graph(G, 'root', radius=distance - 1))
    layer_nodes.append(nodes)

In [67]:
layer_num = [len(x) for x in layer_nodes]
layer_num

[1, 29, 169, 459, 840, 733, 0, 0, 0, 0, 0]

In [68]:
reactome_id=[]
distance_from_root=[]
node_gene_num=[]
for ldx, l in enumerate(layer_nodes):
    for n in l:
        reactome_id.append(n)
        distance_from_root.append(ldx)
        node_gene_num.append(len(gene_pathway.loc[gene_pathway.reactome_id == n,'gene']))

In [69]:
df = pd.DataFrame({'reactome_id':reactome_id,
                   'distance_from_root':distance_from_root,
                   'node_gene_num':node_gene_num})
df = df.drop(0)

In [70]:
maps_node = pd.merge(df, pathways, on='reactome_id', how='left')  # 'inner' merge keeps common rows

In [71]:
maps_edge.to_csv('../../Cytoscape_data/Prostate_maps_edge.csv')
maps_node.to_csv('../../Cytoscape_data/Prostate_maps_node.csv')

# Temp Script

In [81]:
top_level_gene.reactome_id.unique()

array(['R-HSA-9612973', 'R-HSA-1640170', 'R-HSA-1500931', 'R-HSA-8953897',
       'R-HSA-4839726', 'R-HSA-400253', 'R-HSA-73894', 'R-HSA-69306',
       'R-HSA-1266738', 'R-HSA-8963743', 'R-HSA-1643685', 'R-HSA-9748784',
       'R-HSA-1474244', 'R-HSA-74160', 'R-HSA-109582', 'R-HSA-168256',
       'R-HSA-1430728', 'R-HSA-8953854', 'R-HSA-392499', 'R-HSA-397014',
       'R-HSA-112316', 'R-HSA-1852241', 'R-HSA-5357801', 'R-HSA-9609507',
       'R-HSA-1474165', 'R-HSA-9709957', 'R-HSA-162582', 'R-HSA-382551',
       'R-HSA-5653656'], dtype=object)

In [ ]:
genes = prostate_maps[0].index.tolist()
paths = []
for idx, mapp in enumerate(prostate_maps[:-1]):
    print(len(set(mapp.columns.tolist())))
    paths.append(mapp.columns.tolist())

In [ ]:
paths[-1]

In [ ]:
gene_pathway[gene_pathway.reactome_id.isin(paths[-1])]

In [ ]:
top_level_gene.reactome_id.value_counts()

In [ ]:
top_level_gene

In [ ]:
maps_edge[maps_edge.parent.isin(paths[-1])].parent.unique()